#!/usr/bin/env python3
"""Memory-safe table extractor for NitroPDF statements.

Example:
    python3 extract_nitro_tables.py 1.pdf --pages 1-end --out out --method auto --format csv
"""

from __future__ import annotations

import argparse
import gc
import re
import tempfile
import warnings
from pathlib import Path
from typing import Iterable, List, TYPE_CHECKING

if TYPE_CHECKING:
    import pandas as pd

try:
    # Keep noisy ARC4 warning out of CLI output.
    from cryptography.utils import CryptographyDeprecationWarning

    warnings.filterwarnings("ignore", category=CryptographyDeprecationWarning)
except Exception:
    pass


def normalize_cell(value: object) -> str:
    """Normalize extracted cell text."""
    if value is None:
        return ""
    text = str(value).replace("\x00", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text


def normalize_df(df: pd.DataFrame) -> pd.DataFrame:
    cleaned = df.map(normalize_cell)
    # Drop fully-empty rows/columns generated by parsers.
    cleaned = cleaned.loc[~(cleaned == "").all(axis=1)]
    cleaned = cleaned.loc[:, ~(cleaned == "").all(axis=0)]
    return cleaned.reset_index(drop=True)


def make_df(rows: list[list[object]]) -> "pd.DataFrame":
    import pandas as pd

    return pd.DataFrame(rows)


def meaningful(df: pd.DataFrame) -> bool:
    if df.empty:
        return False
    if df.shape[0] < 2 or df.shape[1] < 2:
        return False
    non_empty = (df != "").sum().sum()
    return non_empty >= 4


def is_probably_garbled(df: pd.DataFrame) -> bool:
    """Detect broken font-mapped extraction like '(cid:123)' payloads."""
    values = df.values.tolist()
    cells: list[str] = []
    for row in values:
        for value in row:
            text = normalize_cell(value)
            if text:
                cells.append(text)

    if not cells:
        return True

    joined = " ".join(cells[:500])
    if re.search(r"\(cid:\d+\)", joined):
        return True

    # Garbage extraction often collapses the page into 1-2 giant cells.
    avg_cell_len = sum(len(cell) for cell in cells) / len(cells)
    max_cell_len = max(len(cell) for cell in cells)
    if df.shape[1] <= 2 and (avg_cell_len > 45 or max_cell_len > 240):
        return True

    # Very low whitespace ratio usually means fused binary/glyph text.
    spaces = joined.count(" ")
    if len(joined) > 400 and spaces / max(1, len(joined)) < 0.04:
        return True

    return False


def parse_end_token(token: str, total_pages: int) -> int:
    token = token.strip().lower()
    if token == "end":
        return total_pages
    return int(token)


def parse_pages_spec(spec: str, total_pages: int) -> List[int]:
    """Parse page spec like '1-end', '1,3,6-9'."""
    pages: List[int] = []
    seen = set()
    chunks = [chunk.strip() for chunk in spec.split(",") if chunk.strip()]
    if not chunks:
        raise ValueError("Empty --pages argument")

    for chunk in chunks:
        if "-" in chunk:
            start_s, end_s = chunk.split("-", 1)
            start = 1 if start_s.strip() == "" else parse_end_token(start_s, total_pages)
            end = total_pages if end_s.strip() == "" else parse_end_token(end_s, total_pages)
            if start > end:
                start, end = end, start
            for page in range(start, end + 1):
                if 1 <= page <= total_pages and page not in seen:
                    seen.add(page)
                    pages.append(page)
        else:
            page = parse_end_token(chunk, total_pages)
            if 1 <= page <= total_pages and page not in seen:
                seen.add(page)
                pages.append(page)

    if not pages:
        raise ValueError(f"No valid pages from spec '{spec}' for total_pages={total_pages}")
    return pages


def detect_total_pages(pdf_path: Path, password: str | None) -> int:
    from pypdf import PdfReader

    reader = PdfReader(str(pdf_path))
    if reader.is_encrypted and password:
        reader.decrypt(password)
    return len(reader.pages)


def extract_page_camelot(
    pdf_path: Path, page: int, password: str | None
) -> tuple[List[pd.DataFrame], bool]:
    """Extract tables for a single page using Camelot."""
    import camelot

    out: List[pd.DataFrame] = []
    saw_garbled = False
    for flavor in ("lattice", "stream"):
        try:
            tables = camelot.read_pdf(
                str(pdf_path),
                pages=str(page),
                flavor=flavor,
                password=password,
                strip_text="\n",
            )
        except Exception:
            continue

        for table in tables:
            df = normalize_df(table.df)
            if meaningful(df):
                if is_probably_garbled(df):
                    saw_garbled = True
                    continue
                out.append(df)
        if out:
            break
    return out, saw_garbled


def extract_page_pdfplumber(
    pdf_path: Path, page: int, password: str | None
) -> tuple[List[pd.DataFrame], bool]:
    """Lightweight fallback extraction for a single page."""
    import pdfplumber

    out: List[pd.DataFrame] = []
    saw_garbled = False
    table_settings_variants = (
        {
            "vertical_strategy": "lines",
            "horizontal_strategy": "lines",
            "snap_tolerance": 3,
            "join_tolerance": 3,
        },
        {
            "vertical_strategy": "text",
            "horizontal_strategy": "text",
            "intersection_tolerance": 5,
        },
    )

    with pdfplumber.open(str(pdf_path), password=password) as pdf:
        pdf_page = pdf.pages[page - 1]
        for settings in table_settings_variants:
            try:
                raw_tables = pdf_page.extract_tables(table_settings=settings)
            except Exception:
                continue
            for raw in raw_tables or []:
                if not raw:
                    continue
                df = normalize_df(make_df(raw))
                if meaningful(df):
                    if is_probably_garbled(df):
                        saw_garbled = True
                        continue
                    out.append(df)
            if out:
                break
    return out, saw_garbled


def render_page_to_png(pdf_path: Path, page: int, png_path: Path, dpi: int) -> None:
    """Render a single PDF page to PNG with low memory overhead."""
    import pypdfium2 as pdfium

    pdf = None
    pdf_page = None
    bitmap = None
    image = None
    try:
        pdf = pdfium.PdfDocument(str(pdf_path))
        pdf_page = pdf[page - 1]
        scale = max(1.0, dpi / 72.0)
        bitmap = pdf_page.render(scale=scale)
        image = bitmap.to_pil()
        image.save(str(png_path))
    finally:
        if image is not None:
            image.close()
        if bitmap is not None and hasattr(bitmap, "close"):
            bitmap.close()
        if pdf_page is not None and hasattr(pdf_page, "close"):
            pdf_page.close()
        if pdf is not None and hasattr(pdf, "close"):
            pdf.close()


def extract_page_ocr(
    pdf_path: Path,
    page: int,
    ocr_lang: str,
    ocr_dpi: int,
    ocr_min_confidence: int,
) -> List[pd.DataFrame]:
    """OCR fallback for pages with unreadable text-layer glyph mapping."""
    from img2table.document import Image as Img2TableImage
    from img2table.ocr import TesseractOCR

    out: List[pd.DataFrame] = []
    with tempfile.TemporaryDirectory(prefix="nitro_table_") as tmpdir:
        image_path = Path(tmpdir) / f"page_{page:04d}.png"
        render_page_to_png(pdf_path=pdf_path, page=page, png_path=image_path, dpi=ocr_dpi)

        ocr = TesseractOCR(lang=ocr_lang, n_threads=1)
        image_doc = Img2TableImage(src=str(image_path))
        tables = image_doc.extract_tables(
            ocr=ocr,
            borderless_tables=True,
            min_confidence=ocr_min_confidence,
        )

        for table in tables or []:
            df = normalize_df(table.df)
            if meaningful(df) and not is_probably_garbled(df):
                out.append(df)

    return out


def write_table(df: pd.DataFrame, out_dir: Path, page: int, idx: int, fmt: str) -> None:
    basename = f"page_{page:04d}_table_{idx:02d}"
    if fmt in {"csv", "both"}:
        df.to_csv(out_dir / f"{basename}.csv", index=False)
    if fmt in {"xlsx", "both"}:
        df.to_excel(out_dir / f"{basename}.xlsx", index=False)


def iter_pages(pages: Iterable[int]) -> Iterable[int]:
    for page in pages:
        yield page
        gc.collect()


def run(
    pdf_path: Path,
    pages_spec: str,
    out_dir: Path,
    method: str,
    fmt: str,
    password: str | None,
    ocr_lang: str,
    ocr_dpi: int,
    ocr_min_confidence: int,
) -> None:
    total_pages = detect_total_pages(pdf_path, password=password)
    pages = parse_pages_spec(pages_spec, total_pages=total_pages)
    out_dir.mkdir(parents=True, exist_ok=True)

    total_tables = 0
    print(f"[INFO] PDF pages: {total_pages}")
    print(f"[INFO] Processing pages: {pages[:10]}{'...' if len(pages) > 10 else ''}")
    print(f"[INFO] Method: {method}, Output format: {fmt}")

    for page in iter_pages(pages):
        extracted: List[pd.DataFrame] = []
        saw_garbled = False
        if method in {"auto", "camelot"}:
            camelot_tables, camelot_garbled = extract_page_camelot(
                pdf_path, page, password=password
            )
            extracted = camelot_tables
            saw_garbled = saw_garbled or camelot_garbled
        if not extracted and method in {"auto", "pdfplumber"}:
            plumber_tables, plumber_garbled = extract_page_pdfplumber(
                pdf_path, page, password=password
            )
            extracted = plumber_tables
            saw_garbled = saw_garbled or plumber_garbled
        if not extracted and method in {"auto", "ocr"}:
            try:
                extracted = extract_page_ocr(
                    pdf_path=pdf_path,
                    page=page,
                    ocr_lang=ocr_lang,
                    ocr_dpi=ocr_dpi,
                    ocr_min_confidence=ocr_min_confidence,
                )
                if extracted:
                    print(f"[INFO] Page {page}: OCR fallback used")
            except ImportError as exc:
                print(
                    f"[WARN] Page {page}: OCR fallback unavailable ({exc}). "
                    "Install: pip install img2table pypdfium2 pytesseract"
                )
            except Exception as exc:
                print(f"[WARN] Page {page}: OCR fallback failed ({exc})")

        if not extracted:
            if saw_garbled:
                print(
                    f"[WARN] Page {page}: only garbled text-layer tables found; "
                    "OCR did not return a usable table"
                )
            else:
                print(f"[WARN] Page {page}: no table detected")
            continue

        for idx, df in enumerate(extracted, start=1):
            write_table(df, out_dir=out_dir, page=page, idx=idx, fmt=fmt)
            total_tables += 1

        print(f"[OK] Page {page}: wrote {len(extracted)} table(s)")

    print(f"[DONE] Extracted {total_tables} table(s) into: {out_dir}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Extract tables from NitroPDF statements.")
    parser.add_argument("pdf", help="Input PDF path")
    parser.add_argument("--pages", default="1-end", help="Page spec: 1-end, 1,3,5-9")
    parser.add_argument("--out", default="out", help="Output directory")
    parser.add_argument(
        "--method",
        choices=("auto", "camelot", "pdfplumber", "ocr"),
        default="auto",
        help="Extraction backend",
    )
    parser.add_argument(
        "--format",
        choices=("csv", "xlsx", "both"),
        default="csv",
        help="Output file format",
    )
    parser.add_argument("--password", default=None, help="PDF password (if encrypted)")
    parser.add_argument("--ocr-lang", default="eng", help="Tesseract OCR language")
    parser.add_argument(
        "--ocr-dpi",
        type=int,
        default=150,
        help="OCR render DPI (higher = slower but more accurate)",
    )
    parser.add_argument(
        "--ocr-min-confidence",
        type=int,
        default=45,
        help="Minimum OCR confidence for img2table",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    pdf_path = Path(args.pdf)
    if not pdf_path.exists():
        parser.error(f"PDF not found: {pdf_path}")

    run(
        pdf_path=pdf_path,
        pages_spec=args.pages,
        out_dir=Path(args.out),
        method=args.method,
        fmt=args.format,
        password=args.password,
        ocr_lang=args.ocr_lang,
        ocr_dpi=args.ocr_dpi,
        ocr_min_confidence=args.ocr_min_confidence,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
